# Generated by Django 5.2.3 on 2025-06-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminalname', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('offense', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Houseowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familymember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('HOUSENAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.houseowner')),
            ],
        ),
        migrations.CreateModel(
            name='familiarpersondetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=250)),
                ('HOUSENAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.houseowner')),
            ],
        ),
        migrations.CreateModel(
            name='Criminaldetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=100)),
                ('CRIMINALNAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.criminal')),
                ('HOUSENAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.houseowner')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('HOUSEOWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.houseowner')),
            ],
        ),
        migrations.AddField(
            model_name='houseowner',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login'),
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policestationname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Crimehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenumber', models.CharField(max_length=100)),
                ('date_reposted', models.CharField(max_length=100)),
                ('date_occured', models.CharField(max_length=100)),
                ('crime_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('victim', models.CharField(max_length=100)),
                ('suspect', models.CharField(max_length=100)),
                ('arrest_date', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=100)),
                ('sentence', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('POLICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qrimage', models.CharField(max_length=300)),
                ('HOUSEOWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.houseowner')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('HOUSEOWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.houseowner')),
            ],
        ),
    ]
